#!/bin/bash -ex

# inject version numbers
sed -i "s/version = \"0.0.0\"/version = \"${VERSION}\"/g" pyproject.toml
grep -q "version = \"${VERSION}\"" pyproject.toml
sed -i "s/__version__ = \"0.0.0\"/__version__ = \"${VERSION}\"/g" src/pyspark_dataframe_wrappers/__init__.py
grep -q "__version__ = \"${VERSION}\"" src/pyspark_dataframe_wrappers/__init__.py

# build and upload
python -m pip install --upgrade build twine
python -m build
twine upload dist/*